### ISSUE TITLE
Module dotenv fails to load .env file on jovo run after update to jovo-cli 3.0.2

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-cli#122]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

The `.env` file should load and all items in that file should be available as part of `process.env.X` call

## Current Behavior

This was working running `jovo run` for jovo-cli v2.2.14 but stopped working immediately after updating to jovo-cli v3.0.2.

There are multiple config files in the project: config.js, config.local.js

```
// config.local.js
require('dotenv').config();

module.exports = {
  db: {
    FileDb: {
      enabled: true,
      pathToFile: '../db/db-local.json',
    },
  },
};
```
This config file should load in all values from the `.env` file.

The `app.js` file accesses a value (STAGE) that is in the `.env` file:

```
\\ app.js
const app = new App();
if (process.env.STAGE.includes('local')) { ...
```
The `.env` values are not part of `process.env`. BUT THEY USED TO BE.

### Error log
```
  Message:
  Cannot read property 'includes' of undefined

  Stack:
  TypeError: Cannot read property 'includes' of undefined
      at Object.<anonymous> (C:\dev\voice\shazaml\shazaml-voice-myapp\src\app.js:22:23)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Module.require (internal/modules/cjs/loader.js:849:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (C:\dev\voice\shazaml\shazaml-voice-myapp\src\index.js:4:17)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
```

## Your Environment

* Jovo CLI version used: 3.0.2 (was working immediately before update when version was 2.2.14)
* Operating System: Windows 7

**Comment by rmtuckerphx** [comment]
Installed jovo-cli v3.0.0 and error returned. Reverted to v2.2.14 and it works. This is code that has been working for 10 months that just stopped working.

**Comment by aswetlow** [comment]
Thank you, fixed and published.
