### ISSUE TITLE
CLI "jovo run" doesn't understand app.setAlexaHandler

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-cli#124]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When I execute `jovo run` my project that includes setHandler, setAlexaHandler, and setBixbyHandler should execute without error.

## Current Behavior

I get an error on `jovo run` for my project.

### Error log
```
TypeError: app.setAlexaHandler is not a function
    at Object.<anonymous> (C:\dev\voice\myco\myco-voice-myapp\src\app.js:91:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\dev\voice\myco\myco-voice-myapp\src\index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

## Your Environment

* Jovo CLI version used: 3.0.3
* Operating System: Windows 7

**Comment by jankoenig** [comment]
This might be a problem with updating the npm modules. Could you delete your node_modules folder and package-lock.json, do npm install and try again?

**Comment by jankoenig** [comment]
As discussed in Slack, this seems to be an issue with npm/lerna. More about the update issue here, too: https://community.jovo.tech/t/changes-between-jovo-framework-2-2-25-and-2-2-29/927/3
