### ISSUE TITLE
Error with jovo run --watch

### ISSUE THREAD

**Issue by jdLYNC** [jovotech/jovo-cli#13]
Initially on running `jovo run --watch` I was getting an ENOENT error as below

```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/joshlynch/.config/yarn/global/node_modules/jovo-cli/node_modules/nodemon/bin/nodemon.js ENOENT
    at _errnoException (util.js:999:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

I think this was connected to my already having a global install of nodemon so the file path was in reality `jovo-cli/node_modules/.bin/nodemon/bin/nodemon.js`.

I created a symlink for the nodemon directory in `jovo-cli/node_modules` this fixed the ENOENT but now running `jovo run --watch` is returning an ENOTDIR error instead.

```
internal/child_process.js:340
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at _errnoException (util.js:999:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at Object.exports.spawn (child_process.js:499:9)
    at spawn (/Users/joshlynch/.config/yarn/global/node_modules/cross-spawn/index.js:17:18)
    at CommandInstance.vorpal.command.description.option.option.option.option.action (/Users/joshlynch/.config/yarn/global/node_modules/jovo-cli/commands/run.js:107:24)
    at Session.session.execCommandSet (/Users/joshlynch/.config/yarn/global/node_modules/vorpal/dist/session.js:470:20)
    at Vorpal.vorpal._exec (/Users/joshlynch/.config/yarn/global/node_modules/vorpal/dist/vorpal.js:960:18)
    at Vorpal.vorpal._execQueueItem (/Users/joshlynch/.config/yarn/global/node_modules/vorpal/dist/vorpal.js:751:17)
    at Vorpal.vorpal._queueHandler (/Users/joshlynch/.config/yarn/global/node_modules/vorpal/dist/vorpal.js:735:10)
    at Vorpal.vorpal.exec (/Users/joshlynch/.config/yarn/global/node_modules/vorpal/dist/vorpal.js:682:10)
```

I can't find a solution to this second issue. Presumably this command should be working out of the box? I haven't seen anything regarding a need for configuration in the docs. Help appreciated, cheers.

**Comment by fgnass** [comment]
Just ran into the same issue. The bin path constructed at https://github.com/jovotech/jovo-cli/blob/master/commands/run.js#L40 is wrong if `jovo-cli` is installed locally. I've made good experiences with using https://www.npmjs.com/package/resolve-bin in such cases.
