### ISSUE TITLE
jovo run spams requests after saving changes in jovo project

### ISSUE THREAD

**Issue by andrelandgraf** [jovotech/jovo-cli#213]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

I am following the jovo setup tutorial. I created a new project with `jovo new`. When I run `jovo run`, it successfully creates a webhook url and opens a browser tab for me. The jovo debugger works as expected when I launch intents from the debugger window.

**Not the case for me:** Once I save changes in the jovo project, jovo run re-compiles the project (or restarts jovo run, or whatever). The expected behavior of `jovo run` is documented in the setup guide (e.g. does it watch changes, do I need to restart...).

## Current Behavior

Once I change the code in the jovo project, it spams new requests (one alexa request, one google request) and responses inside the terminal. I need to terminate jovo run for it to stop. This even happens once I revert all my changes, restart jovo run and press "Launch command" within the jovo debugger.

### Error log
```
...
continues forever
...

 >>>>> Request - 2021-05-17T13:19:05.435Z 
{
   "responseId": "ba004821-5bbc-4bf9-8fa0-9c83bfb248e6",
   "queryResult": {
      "queryText": "GOOGLE_ASSISTANT_WELCOME",
      "parameters": {},
      "allRequiredParamsPresent": true,
      "outputContexts": [
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/google_assistant_welcome"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_screen_output"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_audio_output"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/google_assistant_input_type_keyboard"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_web_browser"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_media_response_audio"
         }
      ],
      "intent": {
         "name": "projects/newagent-904be/agent/intents/2c0f131a-8b4e-4cd7-8902-f618a1315895",
         "displayName": "Default Welcome Intent"
      },
      "intentDetectionConfidence": 1,
      "diagnosticInfo": {},
      "languageCode": "en-US"
   },
   "originalDetectIntentRequest": {
      "source": "google",
      "version": "2",
      "payload": {
         "isInSandbox": true,
         "surface": {
            "capabilities": [
               {
                  "name": "actions.capability.WEB_BROWSER"
               },
               {
                  "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
               },
               {
                  "name": "actions.capability.AUDIO_OUTPUT"
               }
            ]
         },
         "inputs": [
            {
               "rawInputs": [
                  {
                     "query": "Talk to my test app",
                     "inputType": "KEYBOARD"
                  }
               ],
               "intent": "actions.intent.MAIN"
            }
         ],
         "user": {
            "lastSeen": "2018-05-15T19:46:52Z",
            "locale": "en-US",
            "userStorage": "{\"userId\":\"17rmqa\"}"
         },
         "conversation": {
            "conversationId": "1526414104011",
            "type": "NEW"
         },
         "availableSurfaces": [
            {
               "capabilities": [
                  {
                     "name": "actions.capability.SCREEN_OUTPUT"
                  },
                  {
                     "name": "actions.capability.AUDIO_OUTPUT"
                  }
               ]
            }
         ]
      }
   },
   "session": "projects/newagent-904be/agent/sessions/1526414104011"
}


 <<<<< Response - 2021-05-17T13:19:05.442Z 
{
   "fulfillmentText": "Hello World! What's your name?",
   "end_interaction": false,
   "outputContexts": [],
   "payload": {
      "google": {
         "expectUserResponse": true,
         "richResponse": {
            "items": [
               {
                  "simpleResponse": {
                     "ssml": "<speak>Hello World! What's your name?</speak>"
                  }
               }
            ]
         },
         "noInputPrompts": [
            {
               "ssml": "<speak>Please tell me your name.</speak>"
            }
         ],
         "userStorage": "{\"userId\":\"17rmqa\"}"
      }
   }
}

 >>>>> Request - 2021-05-17T13:19:05.798Z 
{
   "version": "1.0",
   "session": {
      "new": true,
      "sessionId": "amzn1.echo-api.session.0000000-0000-0000-0000-00000000000",
      "application": {
         "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
      },
      "attributes": {},
      "user": {
         "userId": "vyg0kk"
      }
   },
   "context": {
      "System": {
         "application": {
            "applicationId": "amzn1.echo-sdk-ams.app.000000-d0ed-0000-ad00-000000d00ebe"
         },
         "user": {
            "userId": "vyg0kk"
         },
         "device": {
            "deviceId": "amzn1.ask.device.XXXXXA6LX6BOBJF6XNWQM2ZO4NVVGZRFFEL6PMXKWLOHI36IY3B4XCSZKZPR42RAWCBSQEDNGS746OCC2PKR5KDIVAUY6F2DX5GV2SQAXPD7GMKQRWLG4LFKXFPVLVTXHFGLCQKHB7ZNBKLHQU4SJG6NNGA",
            "supportedInterfaces": {
               "AudioPlayer": {}
            }
         }
      },
      "AudioPlayer": {
         "offsetInMilliseconds": 0,
         "playerActivity": "IDLE"
      }
   },
   "request": {
      "type": "LaunchRequest",
      "requestId": "amzn1.echo-api.request.0000000-0000-0000-0000-00000000000",
      "timestamp": "2021-05-17T13:19:05.794Z",
      "locale": "en-US"
   }
}


 <<<<< Response - 2021-05-17T13:19:05.806Z 
{
   "version": "1.0",
   "response": {
      "shouldEndSession": false,
      "outputSpeech": {
         "type": "SSML",
         "ssml": "<speak>Hello World! What's your name?</speak>"
      },
      "reprompt": {
         "outputSpeech": {
            "type": "SSML",
            "ssml": "<speak>Please tell me your name.</speak>"
         }
      }
   },
   "sessionAttributes": {}
}

 >>>>> Request - 2021-05-17T13:19:05.815Z 
{
   "responseId": "ba004821-5bbc-4bf9-8fa0-9c83bfb248e6",
   "queryResult": {
      "queryText": "GOOGLE_ASSISTANT_WELCOME",
      "parameters": {},
      "allRequiredParamsPresent": true,
      "outputContexts": [
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/google_assistant_welcome"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_screen_output"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_audio_output"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/google_assistant_input_type_keyboard"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_web_browser"
         },
         {
            "name": "projects/newagent-904be/agent/sessions/1526414104011/contexts/actions_capability_media_response_audio"
         }
      ],
      "intent": {
         "name": "projects/newagent-904be/agent/intents/2c0f131a-8b4e-4cd7-8902-f618a1315895",
         "displayName": "Default Welcome Intent"
      },
      "intentDetectionConfidence": 1,
      "diagnosticInfo": {},
      "languageCode": "en-US"
   },
   "originalDetectIntentRequest": {
      "source": "google",
      "version": "2",
      "payload": {
         "isInSandbox": true,
         "surface": {
            "capabilities": [
               {
                  "name": "actions.capability.WEB_BROWSER"
               },
               {
                  "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
               },
               {
                  "name": "actions.capability.AUDIO_OUTPUT"
               }
            ]
         },
         "inputs": [
            {
               "rawInputs": [
                  {
                     "query": "Talk to my test app",
                     "inputType": "KEYBOARD"
                  }
               ],
               "intent": "actions.intent.MAIN"
            }
         ],
         "user": {
            "lastSeen": "2018-05-15T19:46:52Z",
            "locale": "en-US",
            "userStorage": "{\"userId\":\"zvyjjc\"}"
         },
         "conversation": {
            "conversationId": "1526414104011",
            "type": "NEW"
         },
         "availableSurfaces": [
            {
               "capabilities": [
                  {
                     "name": "actions.capability.SCREEN_OUTPUT"
                  },
                  {
                     "name": "actions.capability.AUDIO_OUTPUT"
                  }
               ]
            }
         ]
      }
   },
   "session": "projects/newagent-904be/agent/sessions/1526414104011"
}


 <<<<< Response - 2021-05-17T13:19:05.821Z 
{
   "fulfillmentText": "Hello World! What's your name?",
   "end_interaction": false,
   "outputContexts": [],
   "payload": {
      "google": {
         "expectUserResponse": true,
         "richResponse": {
            "items": [
               {
                  "simpleResponse": {
                     "ssml": "<speak>Hello World! What's your name?</speak>"
                  }
               }
            ]
         },
         "noInputPrompts": [
            {
               "ssml": "<speak>Please tell me your name.</speak>"
            }
         ],
         "userStorage": "{\"userId\":\"zvyjjc\"}"
      }
   }
}
```

## Your Environment

Jovo CLI Version: 3.2.1

Jovo packages of current project:
  jovo-core: 3.5.1
  jovo-db-filedb: 3.5.1
  jovo-framework: 3.5.2
  jovo-platform-alexa: 3.5.4
  jovo-platform-dialogflow: 3.5.2
  jovo-platform-googleassistant: 3.5.3
  jovo-plugin-debugger: 3.5.1
* Operating System: macOS Big Sir 11.3.1
* npm 7.10.0
* node v14.15.3

**Comment by rubenaeg** [comment]
Hm, I'm not sure if this is a CLI issue or an issue with the Debugger itself cc @aswetlow . I'll have a look, thanks for bringing this up.

**Comment by rubenaeg** [comment]
Is your project in JS or in TS?

**Comment by andrelandgraf** [comment]
Sorry, I wanted to add this information to the report. I was able to reproduce the same issue on several new projects both TS and JS.

**Comment by rubenaeg** [comment]
I can't seem to reproduce this. With both TS and JS, on file changes the app just restarts and waits for input.

**Comment by rubenaeg** [comment]
I'm curious about this property inside the Alexa request object:
```js
"user": {
  "userId": "vyg0kk"
}
```
@aswetlow shouldn't this yield `jovo-debugger-user` per default?

**Comment by aswetlow** [comment]
This is a really weird behavior. Can't reproduce it either.

The userId looks like the one generated in unit tests. 

Could you remove the tests in your project?

**Comment by andrelandgraf** [comment]
I removed the tests/ folder that was created via `jovo new` and I was not able to reproduce the error anymore! 

When I run the tests, I receive the following error:

```
    Network Error

      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:84:14)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:18:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:130:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:59:3)
      at EventEmitter.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:397:47)
      at Request.onRequestError (node_modules/request/request.js:877:8)

  console.error
    Error: Error: connect ECONNREFUSED 127.0.0.1:3000
        at Object.dispatchError (/Users/landgan/workspaces/test/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at EventEmitter.<anonymous> (/Users/landgan/workspaces/test/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
        at EventEmitter.emit (events.js:327:22)
        at Request.<anonymous> (/Users/landgan/workspaces/test/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:397:47)
        at Request.emit (events.js:315:20)
        at Request.onRequestError (/Users/landgan/workspaces/test/node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:315:20)
        at Socket.socketErrorListener (_http_client.js:469:9)
        at Socket.emit (events.js:315:20)
        at emitErrorNT (internal/streams/destroy.js:106:8) undefined
```

I am not entierly sure but I think the error also went away when I left the tests but disabled the jest vscode extension. I use VS Code with the [Jest VSCode extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest). Maybe you could install the extension and see if you can reproduce this way?

Either way, deleting the tests resolves the bug already!
