### ISSUE TITLE
Jovo Deploy Alexa Cannot Read Property Length of undefined

### ISSUE THREAD

**Issue by alvarocardenasc** [jovotech/jovo-cli#292]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

Upload skill package

## Current Behavior

it doesn't upload skill package

### Error log
```
🚀 Deploying Alexa Skill [stage: dev]
  ✖ Uploading skill package
x Error: --------------------------------------------------------------------------------
›                                                                                 
› Message:
›  Cannot read property 'length' of undefined
›                                                                                 
› Module:
›  JovoCliCore
```

## Your Environment

* Jovo CLI version used: 4.0.3
* Operating System: macOS 10.15.5

**Comment by jankoenig** [comment]
Hi. Could you share your jovo.project.js file?

**Comment by alvarocardenasc** [comment]
```
const { ProjectConfig } = require('@jovotech/cli-core');
const { AlexaCli } = require('@jovotech/platform-alexa');
const { ServerlessCli } = require('@jovotech/target-serverless');

const project = new ProjectConfig({
  defaultStage: 'dev',
  stages: {
    dev: {
      endpoint: '${JOVO_WEBHOOK_URL}',
      plugins: [
        new AlexaCli({
          locales: {
            en: ['en-US', 'en-GB'],
            es: ['es-US']
          },
          askProfile: 'default'
        }),
        new ServerlessCli()
      ],
    },
    prod: {
      endpoint: process.env.ENDPOINT_PROD,
      plugins: [
        new AlexaCli(
          {
            locales: {
              en: ['en-US', 'en-GB'],
              es: ['es-US']
            },
            askProfile: 'default'
          }
        ),
        new ServerlessCli()
      ],
      // ...
    },
  },
});

module.exports = project;

```

Did I miss something?

**Comment by rubenaeg** [comment]
Hey @alvarocardenasc, I can't reproduce the behaviour on a clean project with your exact configuration posted above. 

![image](https://user-images.githubusercontent.com/37402074/151132893-e71611b6-b4d4-4ca6-9821-3613efae57db.png)

Could you share a bit more about your process here? What are you building, how are you deploying?

**Comment by rubenaeg** [comment]
You can also run `jovo deploy:platform` with the `--debug` flag to show the stack trace.

**Comment by alvarocardenasc** [comment]
This is the stack trace:

`Stack:
›  Error: Cannot read property 'length' of undefined
›      at Task.run (/PATH../node_modules/@jovotech/cli-core/src/Task.ts:105:17)
›      at Task.run (/PATH../node_modules/@jovotech/cli-core/src/Task.ts:65:9)
›      at AlexaHook.deploy (/PATH../node_modules/@jovotech/platform-alexa/src/cli/hooks/DeployHook.ts:226:5)
›      at EventEmitter.run (//PATH../.nvm/versions/node/v14.17.0/lib/node_modules/@jovotech/cli/node_modules/@jovotech/cli-core/src/EventEmitter.ts:53:7)
›      at DeployPlatform.run (/PATH../.nvm/versions/node/v14.17.0/lib/node_modules/@jovotech/cli/node_modules/@jovotech/cli-command-deploy/src/commands/deploy.platform.ts:100:5)
›      at DeployPlatform._run (/PATH../.nvm/versions/node/v14.17.0/lib/node_modules/@jovotech/cli/node_modules/@oclif/command/lib/command.js:43:20)
›      at Config.runCommand (/PATH../.nvm/versions/node/v14.17.0/lib/node_modules/@jovotech/cli/node_modules/@oclif/config/lib/config.js:173:24)
›      at Main.run (/PATH../.nvm/versions/node/v14.17.0/lib/node_modules/@jovotech/cli/node_modules/@oclif/command/lib/main.js:27:9)
›      at Main._run (/PATH../.nvm/versions/node/v14.17.0/lib/node_modules/@jovotech/cli/node_modules/@oclif/command/lib/command.js:43:20)`

**Comment by rubenaeg** [comment]
Could you provide more details about the commands you're using to build and deploy your app?

**Comment by alvarocardenasc** [comment]
command to build:
`jovo build:platform alexa --stage prod`

command to deploy:
`jovo deploy:platform alexa  --stage prod`
