### ISSUE TITLE
JOVO GET CLI 1.1.4 GoogleAction Error

### ISSUE THREAD

**Issue by soltrinox** [jovotech/jovo-cli#34]
jovo get googleAction  --project-id  devtest-xxxxx

   ⠹ Getting Dialogflow Agent files and saving to /platforms/googleAction/dialogflow
/usr/lib/node_modules/jovo-cli/helper/dialogflowUtil.js:364
                        let buf = Buffer.from(JSON.parse(body).response.agentContent, 'base64');
                                                                       ^

TypeError: Cannot read property 'agentContent' of undefined
    at Request._callback (/usr/lib/node_modules/jovo-cli/helper/dialogflowUtil.js:364:72)
    at Request.self.callback (/usr/lib/node_modules/jovo-cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/jovo-cli/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/jovo-cli/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)

jovo

**Comment by aswetlow** [comment]
Hey @soltrinox,
I added a better error handling in v1.1.5. Could you try it again?

**Comment by soltrinox** [comment]
Still getting error 

$bash :  
jovo get googleAction  --project-id  xxxxx-c88a

{ Error: IAM permission 'dialogflow.agents.export' on 'projects/aichart2-c88a' denied.
    at Request._callback (/usr/lib/node_modules/jovo-cli/helper/dialogflowUtil.js:370:47)
    at Request.self.callback (/usr/lib/node_modules/jovo-cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/jovo-cli/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/jovo-cli/node_modules/request/request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
  context:
   { locales: [ 'en-US', 'en' ],
     type: 'googleAction',
     target: 'all',
     skillId: undefined,
     projectId: 'xxxxxx-c88a',
     stage: undefined,
     askProfile: 'default' } }

**Comment by jankoenig** [comment]
Hi @soltrinox, did you create a keyfile as explained here: https://www.jovo.tech/blog/deploy-dialogflow-agent-jovo-cli/

You can then reference it in the `app.json`: 

```
"googleAction": {
  "dialogflow": {
    "projectId": "<your-project-id>",
    "keyFile": "<path-to-key-file>"
    }
}
```

**Comment by soltrinox** [comment]
Thanks i re-ran the auth process for dialogFlow and works now.
