### ISSUE TITLE
Crash Trying To Create New Project With `jovo new <directory>`

### ISSUE THREAD

**Issue by robeberhardt** [jovotech/jovo-cli#50]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
`jovo new <directory_name>` should create a new project

## Current Behavior
` jovo new <directory_name>`

crashing in a call from `jovo-renderer` to `input-string`

### Error log
```
  I'm setting everything up

/Users/rob/.config/yarn/global/node_modules/indent-string/index.js:13
		throw new TypeError(`Expected \`count\` to be a \`number\`, got \`${typeof count}\``);
		^

TypeError: Expected `count` to be a `number`, got `string`
    at module.exports (/Users/rob/.config/yarn/global/node_modules/indent-string/index.js:13:9)
    at renderHelper (/Users/rob/.config/yarn/global/node_modules/jovo-cli/utils/jovoRenderer.js:22:25)
    at render (/Users/rob/.config/yarn/global/node_modules/jovo-cli/utils/jovoRenderer.js:57:15)
    at Timeout._id.setInterval [as _onTimeout] (/Users/rob/.config/yarn/global/node_modules/jovo-cli/utils/jovoRenderer.js:89:13)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

### Solution
there was a breaking change in [input-string](https://github.com/sindresorhus/indent-string/commit/22641764d94e3837e4f1888a29c735c07c373990) that swapped the order of two params

the version of input-string packaged with [listr](https://github.com/SamVerschueren/listr) uses `(str, indent, count)` but I had a newer version of input-string in my global modules that uses `(str, count, opts)`

## Your Environment

* Jovo CLI version used: 1.4.0
* node 10.8.0 (error also occurred in 8.11.3 and 9.9.0)
* Operating System: Mac OS 10.13.6

**Comment by janober** [comment]
Hello,
thanks a lot. That issue got fixed in v2 of the CLI. It got already released as beta and we will release the official version in the next days.
