### ISSUE TITLE
Amazon Get Skill ERROR

### ISSUE THREAD

**Issue by soltrinox** [jovotech/jovo-cli#52]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Import the Alexa Skill and reverse to Jovo Markup structure

## Current Behavior
Fails on Jovo Get  : 

$   jovo get alexaSkill -b   --skill-id amzn1.ask.skill.xxxxxx-xxxx-xxxxx-xxxxxxxxxx

### Error log
```



 Getting Alexa Skill model files and saving to /platforms/alexaSkill/models

{ Error: /usr/local/lib/node_modules/ask-cli/node_modules/simple-oauth2/lib/client/access-token.js:20    if ('expires_at' in this.token) {
                     

TypeError: Cannot use 'in' operator to search for 'expires_at' in undefined
    at new AccessToken (/usr/local/lib/node_modules/ask-cli/node_modules/simple-oauth2/lib/client/access-token.js:20:22)
    at Object.createAccessToken [as create] (/usr/local/lib/node_modules/ask-cli/node_modules/simple-oauth2/lib/client/access-token.js:37:12)
    at isTokenExpired (/usr/local/lib/node_modules/ask-cli/lib/utils/oauth-wrapper.js:97:35)
    at Object.tokenRefreshAndRead (/usr/local/lib/node_modules/ask-cli/lib/utils/oauth-wrapper.js:84:10)
    at Object.module.exports.requestWithUrl (/usr/local/lib/node_modules/ask-cli/lib/api/request-wrapper.js:45:18)
    at Object.module.exports.request (/usr/local/lib/node_modules/ask-cli/lib/api/request-wrapper.js:26:20)
    at Object.callGetSkill (/usr/local/lib/node_modules/ask-cli/lib/api/api-wrapper.js:157:20)
    at Command.handle (/usr/local/lib/node_modules/ask-cli/lib/api/skill.js:96:20)
    at Command.listener (/usr/local/lib/node_modules/ask-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/ask-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/ask-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/ask-cli/bin/ask-api.js:22:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

    at Object.getAskError (/usr/local/lib/node_modules/jovo-cli/helper/alexaUtil.js:786:16)
    at exec (/usr/local/lib/node_modules/jovo-cli/helper/alexaUtil.js:673:44)
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  context:
   { locales: [ 'en-us', 'en' ],
     type: 'alexaSkill',
     target: 'all',
     skillId: 'amzn1.ask.skill.xxxxxx-xxxx-xxxxx-xxxxxxxxxx',
     projectId: 'xxxxx2-xxxxxx',
     stage: '',
     askProfile: 'default',
     info: 'Info: ' } }
```

## Your Environment

* Jovo CLI version used: 1.2.1
* Operating System:  Ubuntu 16.04

**Comment by aswetlow** [comment]
It's thrown by the OAuth client that is used by the ASK-CLI. It looks like your token is not valid. 
Please check it with: `ask api get-skill-status <skill-id>`
