### ISSUE TITLE
TypeError: _.get is not a function

### ISSUE THREAD

**Issue by QuentinDela** [jovotech/jovo-cli#78]
## I'm submitting a...
- [X] Bug report

## Current Behaviour
I am usually using jovo-cli globally and have no issues.
I wanted to have the jovo-cli run from the project folder to use VS Code debugger.
When I install jovo-cli in dev dependencies, the server won't run with `jovo run`.

### Error log
```
TypeError: _.get is not a function
    at Project.getStage (/Users/MyProject/node_modules/jovo-cli-core/dist/src/Project.js:360:19)
    at CommandInstance.vorpalCommand.action (/Users/MyProject/node_modules/jovo-cli/dist/commands/run.js:49:31)
    at <anonymous>
 Unhandled Rejection at: Promise Promise {
  <rejected> Error: true
    at Vorpal.<anonymous> (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:168:17)
    at callback (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:830:22)
    at /Users/MyProject/node_modules/vorpal/dist/vorpal.js:961:7
    at Session._commandSetCallback (/Users/MyProject/node_modules/vorpal/dist/session.js:440:5)
    at Session.session.completeCommand (/Users/MyProject/node_modules/vorpal/dist/session.js:520:12)
    at onCompletion (/Users/MyProject/node_modules/vorpal/dist/session.js:450:10)
    at /Users/MyProject/node_modules/vorpal/dist/session.js:481:7
    at <anonymous> } reason: Error: true
    at Vorpal.<anonymous> (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:168:17)
    at callback (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:830:22)
    at /Users/MyProject/node_modules/vorpal/dist/vorpal.js:961:7
    at Session._commandSetCallback (/Users/MyProject/node_modules/vorpal/dist/session.js:440:5)
    at Session.session.completeCommand (/Users/MyProject/node_modules/vorpal/dist/session.js:520:12)
    at onCompletion (/Users/MyProject/node_modules/vorpal/dist/session.js:450:10)
    at /Users/MyProject/node_modules/vorpal/dist/session.js:481:7
    at <anonymous>
Unhandled Rejection at: Promise Promise {
  <rejected> Error: true
    at Vorpal.<anonymous> (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:168:17)
    at callback (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:830:22)
    at /Users/MyProject/node_modules/vorpal/dist/vorpal.js:961:7
    at Session._commandSetCallback (/Users/MyProject/node_modules/vorpal/dist/session.js:440:5)
    at Session.session.completeCommand (/Users/MyProject/node_modules/vorpal/dist/session.js:520:12)
    at onCompletion (/Users/MyProject/node_modules/vorpal/dist/session.js:450:10)
    at /Users/MyProject/node_modules/vorpal/dist/session.js:481:7
    at <anonymous> } reason: Error: true
    at Vorpal.<anonymous> (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:168:17)
    at callback (/Users/MyProject/node_modules/vorpal/dist/vorpal.js:830:22)
    at /Users/MyProject/node_modules/vorpal/dist/vorpal.js:961:7
    at Session._commandSetCallback (/Users/MyProject/node_modules/vorpal/dist/session.js:440:5)
    at Session.session.completeCommand (/Users/MyProject/node_modules/vorpal/dist/session.js:520:12)
    at onCompletion (/Users/MyProject/node_modules/vorpal/dist/session.js:450:10)
    at /Users/MyProject/node_modules/vorpal/dist/session.js:481:7
    at <anonymous>
```

## Your Environment
* Jovo CLI version used: 2.0.6
* Operating System: MacOS 10.14.1

**Comment by janober** [comment]
Ah yes, you are right. Thanks. Got added. The new version the fix will be released soon.
