### ISSUE TITLE
promisify is not a function

### ISSUE THREAD

**Issue by NovaGL** [jovotech/jovo-cli#80]
## I'm submitting a...

- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

Can you let me know what I am doing wrong? Using Raspbian.

```

const copyFileAsync = promisify(fs.copyFile);
                      ^

TypeError: promisify is not a function
    at Object.<anonymous> (/root/.nvm/versions/node/v7.10.1/lib/node_modules/jovo-cli/node_modules/jovo-cli-core/dist/src/Project.js:5:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.10.1/lib/node_modules/jovo-cli/node_modules/jovo-cli-core/dist/src/index.js:9:10)
    at Module._compile (module.js:571:32)

`

**Comment by jankoenig** [comment]
You're using an old version of Node. Please update to 8.10
