### ISSUE TITLE
jovo build fails RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out

### ISSUE THREAD

**Issue by stuart-clark-45** [jovotech/jovo-cli#92]
## I'm submitting a...

- [ x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Hi there, I am having trouble running `jovo build` any help would be greatly appreciated!

## Current Behavior
see below

### Error log
```
Stuarts-MacBook-Pro:voice stuart$ npm i -g jovo-cli
/Users/stuart/.nvm/versions/node/v10.4.0/bin/jovo -> /Users/stuart/.nvm/versions/node/v10.4.0/lib/node_modules/jovo-cli/dist/index.js
+ jovo-cli@2.2.8
updated 1 package in 41.757s
Stuarts-MacBook-Pro:voice stuart$ jovo new my-test-app

  I'm setting everything up

    ✔ Creating new directory /my-test-app
    ✔ Downloading and extracting template helloworld
    ✔ Installing npm dependencies

  Installation completed.



Stuarts-MacBook-Pro:voice stuart$ cd my-test-app/
Stuarts-MacBook-Pro:my-test-app stuart$ ls
LICENSE           models            package-lock.json project.js        test
README.md         node_modules      package.json      src
Stuarts-MacBook-Pro:my-test-app stuart$ jovo build

 jovo build:  Create and update platform specific files in /platforms folder
   >> Learn more: https://jovo.tech/docs/cli/build

    ✔ Initializing build process
      ✔ Collecting platform configuration from project.js
        Platforms: alexaSkill, googleAction
      ✔ Collecting Jovo Language Model files from /models folder
        Locales: en-US
      ✔ Validate Model-Files
        ✔ en-US

    ✔ Creating Alexa Skill project files
      Path: ./platforms/alexaSkill
      ✔ Creating Alexa project files
        ✔ skill.json
      ✔ Creating Alexa Interaction Model
        Path: ./platforms/alexaSkill/models
        ✔ en-US

    ✔ Creating Google Action project files
      Path: ./platforms/googleAction
      ✔ Creating Dialogflow Agent
        Path: ./platforms/googleAction/dialogflow
        ✔ agent.json
        ✔ package.json
      ✔ Creating Language Model
        Path: ./platforms/googleAction/dialogflow/intents, ./platforms/googleAction/dialog
flow/entities
        ✔ en-US

  Build completed.



Stuarts-MacBook-Pro:my-test-app stuart$ jovo deploy

    ❯ Bundle Project
      ✔ Copy source code to "./bundle"
      ✖ Run "npm install --production"
       -> Command failed: npm run bundle
[10:31:42] 'prepareProject' errored after
          50 ms
[10:31:42] RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out
          of range. Received 33206
    at Object.fs.fchmod (fs.js:1058:11)
    at
          Object.fchmod
          (/Users/stuart/WBB/voice/my-test-app/node_modules/graceful-fs/polyfills.js
          :235:19)
    at mode
          (/Users/stuart/WBB/voice/my-test-app/node_modules/vinyl-fs/lib/file-operat
          ions.js:237:10)
    at onStat
          (/Users/stuart/WBB/voice/my-test-app/node_modules/vinyl-fs/lib/file-operat
          ions.js:227:14)
    at callback
          (/Users/stuart/WBB/voice/my-test-app/node_modules/graceful-fs/polyfills.js
          :289:20)
    at FSReqWrap.oncomplete (fs.js:185:5)
[10:31:42] 'default'
          errored after 56 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
          jovo-sample-voice-app-nodejs@2.0.2 bundle: `gulp --gulpfile
          node_modules/jovo-framework/gulpfile.js --cwd ./`
npm ERR! Exit status
          1
npm ERR!
npm ERR! Failed at the jovo-sample-voice-app-nodejs@2.0.2
          bundle script.
npm ERR! This is probably not a problem with npm. There is
          likely additional logging output above.

npm ERR! A complete log of this
          run can be found in:
npm ERR!
          /Users/stuart/.npm/_logs/2019-07-11T09_31_42_804Z-debug.log
        Zip "./bundle" folder
      Deploying Alexa Skill
      Deploying Google Action
Stuarts-MacBook-Pro:my-test-app stuart$
```

## Your Environment
Jovo CLI Version: 2.2.8

Jovo packages of current project:
  jovo-cms-i18next: 2.2.11
  jovo-core: 2.2.10
  jovo-db-filedb: 2.2.10
  jovo-framework: 2.2.13
  jovo-platform-alexa: 2.2.15
  jovo-platform-dialogflow: 2.2.11
  jovo-platform-googleassistant: 2.2.13
  jovo-plugin-debugger: 2.2.11

ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

**Comment by jankoenig** [comment]
Hey there, which version of Node are you using? (`node -v`)?

According to [this thread](https://community.jovo.tech/t/deploying-fails-for-googleaction/436), an outdated version could be the problem. Make sure that you use at least 8.10

**Comment by stuart-clark-45** [comment]
Hey @jankoenig,

Thanks for getting back, afraid that's not the issue

```
Stuarts-MacBook-Pro:my-test-app stuart$ node -v
v10.4.0
```

**Comment by stuart-clark-45** [comment]
Hey @jankoenig do you have any ideas on what this could be? Is there a development guide anywhere I am happy to try and fix it myself could just do with a few pointers on how the project works?

**Comment by stuart-clark-45** [comment]
Updated to v10.16.0 and that seemed to sort it. Cheers for the help 👍
